set nocompatible

" General
set history=700
filetype plugin on
filetype indent on
set autoread

let mapleader = ","
let g:mapleader = ","
nmap <leader>w :w!<cr>

" UI
set so=7

set wildmenu
set wildignore=*.o,*~,*.pyc

set ruler
set cmdheight=2
set hid
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

set ignorecase
set smartcase
set hlsearch
set incsearch

set lazyredraw
set magic

set showmatch
set mat=2

" Colours/Fonts
syntax enable
colorscheme desert
set background=dark

if has("gui_running")
    set guioptions-=T
    set guioptions+=e
    set t_Co=256
    set guitablabel=%M\ %t
endif

set encoding=utf8
set ffs=unix,dos,mac

" Files
set nobackup
set nowb
set noswapfile

if v:version >= 703
    set undodir=~/.vim/undofiles
    set undofile

    set colorcolumn=+1
endif

" Tabs!
autocmd Filetype python,php,javascript,yaml,lua setlocal expandtab
set smarttab
set shiftwidth=4
set tabstop=4
autocmd Filetype javascript,yaml setlocal tabstop=2 shiftwidth=2

set lbr
set tw=500
set autoindent
set smartindent

" Visual mode
vnoremap <silent> * :call VisualSelection('f')<CR>
vnoremap <silent> # :call VisualSelection('b')<CR>

" Moving around
map <space> /
map <c-space> ?
map <silent> <leader><cr> :noh<cr>

map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif
set viminfo^=%

" Status
set laststatus=2

set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %c,%l/%L\ %P

" Helper functions

function! HasPaste()
    if &paste
        return 'PASTE MODE  '
    en
    return ''
endfunction

fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun
autocmd FileType c,cpp,java,javascript,php,ruby,python,lua autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()

